use serde::{Deserialize, Serialize};

use crate::state::ProjectState;

/// Domain events that flow through the plugin system.
///
/// Each plugin receives events and can react accordingly.
/// Events are the communication backbone between modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum SynapseEvent {
    /// System is starting up
    SystemInit {
        project_root: String,
        state: ProjectState,
    },
    /// A file was modified (or created)
    FileChanged { path: String, kind: FileChangeKind },
    /// A symbol was resolved by the cortex
    SymbolResolved {
        name: String,
        file: String,
        line: usize,
    },
    /// DLP found sensitive content
    SecurityAlert {
        rule: String,
        severity: Severity,
        context: String,
    },
    /// A command was evaluated by the sentinel
    CommandEvaluated { command: String, allowed: bool },
    /// Git state changed (new commit, branch switch, etc.)
    GitStateChanged {
        head: String,
        branch: Option<String>,
    },
    /// Compiler diagnostics updated for a project path
    DiagnosticUpdated {
        /// Number of errors
        errors: usize,
        /// Number of warnings
        warnings: usize,
    },
    /// Telemetry spans received from OTLP
    TelemetryUpdate {
        /// Number of spans in this batch
        spans_received: usize,
        /// File path of the hottest span (if any)
        hotspot_file: Option<String>,
        /// Duration of the hottest span in ms (if any)
        hotspot_duration_ms: Option<f64>,
    },
    /// Code graph indexing completed in the background.
    /// Fired by CortexPlugin after async indexing finishes.
    IndexingComplete,
    /// Tantivy search index is warm and ready for queries.
    /// Fired by SearchPlugin after background indexing completes.
    SearchReady,
    /// Architecture violation detected by the Architect linter (D58).
    ArchitectureViolation {
        rule: String,
        severity: String,
        modules: Vec<String>,
    },
    /// A compiler auto-fix proposal was generated by the RepairOrchestrator.
    AutoFixProposed {
        proposal_id: String,
        file_path: String,
        error_code: String,
        preview: String,
    },
    /// An auto-fix was applied (or reverted on failure).
    AutoFixApplied {
        proposal_id: String,
        file_path: String,
        success: bool,
    },
    /// System is shutting down
    SystemShutdown,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FileChangeKind {
    Created,
    Modified,
    Deleted,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Severity {
    Low,
    Medium,
    High,
    Critical,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn file_change_kind_serde_roundtrip() {
        for kind in [
            FileChangeKind::Created,
            FileChangeKind::Modified,
            FileChangeKind::Deleted,
        ] {
            let json = serde_json::to_string(&kind).unwrap();
            let back: FileChangeKind = serde_json::from_str(&json).unwrap();
            assert_eq!(format!("{:?}", kind), format!("{:?}", back));
        }
    }

    #[test]
    fn severity_serde_roundtrip() {
        for sev in [Severity::Low, Severity::Medium, Severity::High, Severity::Critical] {
            let json = serde_json::to_string(&sev).unwrap();
            let back: Severity = serde_json::from_str(&json).unwrap();
            assert_eq!(sev, back);
        }
    }

    #[test]
    fn event_serde_tagged() {
        let event = SynapseEvent::IndexingComplete;
        let json = serde_json::to_string(&event).unwrap();
        assert!(json.contains("\"type\""));
        assert!(json.contains("indexing_complete"));
    }

    #[test]
    fn event_file_changed_roundtrip() {
        let event = SynapseEvent::FileChanged {
            path: "src/main.rs".into(),
            kind: FileChangeKind::Modified,
        };
        let json = serde_json::to_string(&event).unwrap();
        let back: SynapseEvent = serde_json::from_str(&json).unwrap();
        if let SynapseEvent::FileChanged { path, .. } = back {
            assert_eq!(path, "src/main.rs");
        } else {
            panic!("Expected FileChanged variant");
        }
    }

    #[test]
    fn event_security_alert_roundtrip() {
        let event = SynapseEvent::SecurityAlert {
            rule: "aws_key".into(),
            severity: Severity::Critical,
            context: "line 42".into(),
        };
        let json = serde_json::to_string(&event).unwrap();
        let back: SynapseEvent = serde_json::from_str(&json).unwrap();
        if let SynapseEvent::SecurityAlert { rule, severity, .. } = back {
            assert_eq!(rule, "aws_key");
            assert_eq!(severity, Severity::Critical);
        } else {
            panic!("Expected SecurityAlert variant");
        }
    }
}
